"""SQLAlchemy models.

Note on dates: next_due and Interaction.date are stored as ISO date strings
(YYYY-MM-DD) to match exactly what the React frontend produces and consumes.
This keeps the POC simple. Move these to real DATE columns when you harden for
production if you want server-side date math.
"""
import uuid

from sqlalchemy import Boolean, Column, Float, Integer, String, Text, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship

from database import Base


def _contact_id() -> str:
    return "c" + uuid.uuid4().hex[:12]


def _interaction_id() -> str:
    return "i" + uuid.uuid4().hex[:12]


def _user_id() -> str:
    return "u" + uuid.uuid4().hex[:12]


def _todo_id() -> str:
    return "t" + uuid.uuid4().hex[:12]


def _place_id() -> str:
    return "p" + uuid.uuid4().hex[:12]


def _trip_id() -> str:
    return "tr" + uuid.uuid4().hex[:11]


def _visit_id() -> str:
    return "v" + uuid.uuid4().hex[:12]


class User(Base):
    """A profile that owns its own set of contacts. No password — selecting a
    user is a client-side switch for now. When SSO lands, this table gains the
    Microsoft object id / email and the rest of the model is unchanged."""

    __tablename__ = "users"

    id = Column(String, primary_key=True, default=_user_id)
    name = Column(String, nullable=False)
    # Set once the profile is linked to a Microsoft Entra (M365) identity.
    microsoft_oid = Column(String, nullable=True, unique=True, index=True)
    email = Column(String, nullable=True)
    # Serialized MSAL token cache (delegated Graph refresh/access tokens) for
    # the starbot chat. Only populated after the user signs in with Microsoft.
    m365_token_cache = Column(Text, nullable=True)
    created_at = Column(DateTime, server_default=func.now())

    contacts = relationship(
        "Contact",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    todos = relationship(
        "Todo",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    places = relationship(
        "Place",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    trips = relationship(
        "Trip",
        back_populates="owner",
        cascade="all, delete-orphan",
    )


class Contact(Base):
    __tablename__ = "contacts"

    id = Column(String, primary_key=True, default=_contact_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name = Column(String, nullable=False)
    company = Column(String, default="")
    role = Column(String, default="")
    email = Column(String, default="")
    phone = Column(String, default="")
    category = Column(String, default="bd")  # bd|gc|vendor|property|client|sub|designer|insurance|other
    category_label = Column(String, nullable=True)  # free-text label when category == "other"
    next_action = Column(Text, default="")
    next_due = Column(String, default="")    # ISO date string, may be empty
    notes = Column(Text, default="")
    # NOTE: card scans still prefill contacts (cards.py), but the photo itself is
    # no longer stored — the card_image columns were dropped 2026-07 to save DB
    # space (one-time export lives in ~/Documents/starbot-card-image-backup).
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="contacts")
    interactions = relationship(
        "Interaction",
        back_populates="contact",
        cascade="all, delete-orphan",
    )


class Interaction(Base):
    __tablename__ = "interactions"

    id = Column(String, primary_key=True, default=_interaction_id)
    contact_id = Column(String, ForeignKey("contacts.id", ondelete="CASCADE"), nullable=False)
    date = Column(String, nullable=False)  # ISO date string
    note = Column(Text, nullable=False)

    contact = relationship("Contact", back_populates="interactions")


class Todo(Base):
    """A task on a user's board. Usually generated by the chat from emails/
    calendar (source + source_link point back at the origin), but users can
    also add and manage items on the Tasks tab (kanban: todo/in_progress/done,
    optional priority)."""

    __tablename__ = "todos"

    id = Column(String, primary_key=True, default=_todo_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    text = Column(Text, nullable=False)
    due = Column(String, default="")          # ISO date string, may be empty
    source = Column(String, default="")       # e.g. 'Email: "RE: invoice" — Bob, Jun 30'
    source_link = Column(String, default="")  # Outlook/SharePoint webLink to the origin
    status = Column(String, nullable=False, default="todo")  # todo | in_progress | done
    priority = Column(String, nullable=True)  # low | medium | high | None
    # Legacy flag, kept in sync with status (done == (status == 'done')) so
    # older API payloads and chat tool outputs keep working.
    done = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="todos")


class Place(Base):
    """A saved address on a user's mileage tab — the self-building address book
    of job sites. Sourced from calendar scans, manual adds, or saved trips.
    Coordinates are cached so repeat visits never re-geocode."""

    __tablename__ = "places"

    id = Column(String, primary_key=True, default=_place_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    label = Column(String, default="")     # e.g. "Hernandez job — Chula Vista"
    address = Column(String, nullable=False)
    lat = Column(Float, nullable=True)
    lon = Column(Float, nullable=True)
    source = Column(String, default="manual")  # manual | calendar | trip
    times_used = Column(Integer, nullable=False, default=0)
    last_used = Column(String, default="")     # ISO date string
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="places")


class PlaceVisit(Base):
    """A day-stamp on a place: 'the calendar had this user at this address on
    this date'. Written by the calendar scan (one row per address+date, so
    re-scanning a window never duplicates); read as day groups that load a
    whole day's stops into the trip form. This is the bridge between calendar
    events and the day-grouped mileage report."""

    __tablename__ = "place_visits"

    id = Column(String, primary_key=True, default=_visit_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    place_id = Column(
        String, ForeignKey("places.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date of the calendar event
    # Short business-purpose label — the event's title when that's clear,
    # otherwise composed from the event's own content (never invented).
    # Doubles as the IRS "business purpose" column on the exported report.
    label = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now())


class Event(Base):
    """One usage-telemetry row: who did what, where, when. Written best-effort
    by telemetry.log_event (a failure there never breaks the feature being
    observed); read only by the /api/stats aggregate summary."""

    __tablename__ = "events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, nullable=True, index=True)
    area = Column(String, nullable=False)    # chat | crm | tasks | mileage | connector | auth
    action = Column(String, nullable=False)  # e.g. "message", "tool:read_email", "trip_saved"
    detail = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now(), index=True)


class Trip(Base):
    """One saved mileage calculation (a day's route). Legs are stored as the
    JSON the routing endpoint returned: [{from, to, miles, minutes}]."""

    __tablename__ = "trips"

    id = Column(String, primary_key=True, default=_trip_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date string (auto-stamped at save)
    legs_json = Column(Text, nullable=False)
    total_miles = Column(Float, nullable=False)
    # $/mile chosen at entry time — stored per trip so a special-case rate
    # (e.g. installer payments) never re-prices other entries in the log.
    rate = Column(Float, nullable=True)
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="trips")
