"""SQLAlchemy models.

Note on dates: next_due and Interaction.date are stored as ISO date strings
(YYYY-MM-DD) to match exactly what the React frontend produces and consumes.
This keeps the POC simple. Move these to real DATE columns when you harden for
production if you want server-side date math.
"""
import uuid

from sqlalchemy import Boolean, Column, Float, Integer, String, Text, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship

from database import Base


def _contact_id() -> str:
    return "c" + uuid.uuid4().hex[:12]


def _interaction_id() -> str:
    return "i" + uuid.uuid4().hex[:12]


def _user_id() -> str:
    return "u" + uuid.uuid4().hex[:12]


def _todo_id() -> str:
    return "t" + uuid.uuid4().hex[:12]


def _place_id() -> str:
    return "p" + uuid.uuid4().hex[:12]


def _trip_id() -> str:
    return "tr" + uuid.uuid4().hex[:11]


def _visit_id() -> str:
    return "v" + uuid.uuid4().hex[:12]


def _account_id() -> str:
    return "a" + uuid.uuid4().hex[:12]


def _acct_contact_id() -> str:
    return "ac" + uuid.uuid4().hex[:11]


def _acct_interaction_id() -> str:
    return "ai" + uuid.uuid4().hex[:11]


def _dismiss_id() -> str:
    return "d" + uuid.uuid4().hex[:12]


class User(Base):
    """A profile that owns its own set of contacts. No password — selecting a
    user is a client-side switch for now. When SSO lands, this table gains the
    Microsoft object id / email and the rest of the model is unchanged."""

    __tablename__ = "users"

    id = Column(String, primary_key=True, default=_user_id)
    name = Column(String, nullable=False)
    # Set once the profile is linked to a Microsoft Entra (M365) identity.
    microsoft_oid = Column(String, nullable=True, unique=True, index=True)
    email = Column(String, nullable=True)
    # Serialized MSAL token cache (delegated Graph refresh/access tokens) for
    # the starbot chat. Only populated after the user signs in with Microsoft.
    m365_token_cache = Column(Text, nullable=True)
    created_at = Column(DateTime, server_default=func.now())

    contacts = relationship(
        "Contact",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    todos = relationship(
        "Todo",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    places = relationship(
        "Place",
        back_populates="owner",
        cascade="all, delete-orphan",
    )
    trips = relationship(
        "Trip",
        back_populates="owner",
        cascade="all, delete-orphan",
    )


class Contact(Base):
    __tablename__ = "contacts"

    id = Column(String, primary_key=True, default=_contact_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name = Column(String, nullable=False)
    company = Column(String, default="")
    role = Column(String, default="")
    email = Column(String, default="")
    phone = Column(String, default="")       # primary number (first of phones_json); kept for the table + back-compat
    phones_json = Column(Text, default="[]")  # JSON list of {type, number} — cell/work/home/other
    category = Column(String, default="bd")  # bd|gc|vendor|property|client|sub|designer|insurance|healthcare|other
    category_label = Column(String, nullable=True)  # free-text label when category == "other"
    next_action = Column(Text, default="")
    next_due = Column(String, default="")    # ISO date string, may be empty
    notes = Column(Text, default="")
    # NOTE: card scans still prefill contacts (cards.py), but the photo itself is
    # no longer stored — the card_image columns were dropped 2026-07 to save DB
    # space (one-time export lives in ~/Documents/starbot-card-image-backup).
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="contacts")
    interactions = relationship(
        "Interaction",
        back_populates="contact",
        cascade="all, delete-orphan",
    )


class Interaction(Base):
    __tablename__ = "interactions"

    id = Column(String, primary_key=True, default=_interaction_id)
    contact_id = Column(String, ForeignKey("contacts.id", ondelete="CASCADE"), nullable=False)
    date = Column(String, nullable=False)  # ISO date string
    note = Column(Text, nullable=False)

    contact = relationship("Contact", back_populates="interactions")


class Todo(Base):
    """A task on a user's board. Usually generated by the chat from emails/
    calendar (source + source_link point back at the origin), but users can
    also add and manage items on the Tasks tab (kanban: todo/in_progress/done,
    optional priority)."""

    __tablename__ = "todos"

    id = Column(String, primary_key=True, default=_todo_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    text = Column(Text, nullable=False)
    due = Column(String, default="")          # ISO date string, may be empty
    source = Column(String, default="")       # e.g. 'Email: "RE: invoice" — Bob, Jun 30'
    source_link = Column(String, default="")  # Outlook/SharePoint webLink to the origin
    status = Column(String, nullable=False, default="todo")  # todo | in_progress | done
    priority = Column(String, nullable=True)  # low | medium | high | None
    # Legacy flag, kept in sync with status (done == (status == 'done')) so
    # older API payloads and chat tool outputs keep working.
    done = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="todos")


class Place(Base):
    """A saved address on a user's mileage tab — the self-building address book
    of job sites. Sourced from calendar scans, manual adds, or saved trips.
    Coordinates are cached so repeat visits never re-geocode."""

    __tablename__ = "places"

    id = Column(String, primary_key=True, default=_place_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    label = Column(String, default="")     # e.g. "Hernandez job — Chula Vista"
    address = Column(String, nullable=False)
    lat = Column(Float, nullable=True)
    lon = Column(Float, nullable=True)
    source = Column(String, default="manual")  # manual | calendar | trip
    times_used = Column(Integer, nullable=False, default=0)
    last_used = Column(String, default="")     # ISO date string
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="places")


class PlaceVisit(Base):
    """A day-stamp on a place: 'the calendar had this user at this address on
    this date'. Written by the calendar scan (one row per address+date, so
    re-scanning a window never duplicates); read as day groups that load a
    whole day's stops into the trip form. This is the bridge between calendar
    events and the day-grouped mileage report."""

    __tablename__ = "place_visits"

    id = Column(String, primary_key=True, default=_visit_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    place_id = Column(
        String, ForeignKey("places.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date of the calendar event
    # Short business-purpose label — the event's title when that's clear,
    # otherwise composed from the event's own content (never invented).
    # Doubles as the IRS "business purpose" column on the exported report.
    label = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now())


class DismissedEmail(Base):
    """A flagged email a user dismissed from the Tasks 'Replies needed' lane, so
    a refresh won't re-surface it even while the Outlook flag is still set.
    `message_id` is the Graph message id. Per-user; cascade-deleted with the user."""

    __tablename__ = "dismissed_emails"

    id = Column(String, primary_key=True, default=_dismiss_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    message_id = Column(String, nullable=False)
    created_at = Column(DateTime, server_default=func.now())


class Event(Base):
    """One usage-telemetry row: who did what, where, when. Written best-effort
    by telemetry.log_event (a failure there never breaks the feature being
    observed); read only by the /api/stats aggregate summary."""

    __tablename__ = "events"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, nullable=True, index=True)
    area = Column(String, nullable=False)    # chat | crm | tasks | mileage | connector | auth
    action = Column(String, nullable=False)  # e.g. "message", "tool:read_email", "trip_saved"
    detail = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now(), index=True)


class Trip(Base):
    """One saved mileage calculation (a day's route). Legs are stored as the
    JSON the routing endpoint returned: [{from, to, miles, minutes}]."""

    __tablename__ = "trips"

    id = Column(String, primary_key=True, default=_trip_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date string (auto-stamped at save)
    legs_json = Column(Text, nullable=False)
    total_miles = Column(Float, nullable=False)
    # $/mile chosen at entry time — stored per trip so a special-case rate
    # (e.g. installer payments) never re-prices other entries in the log.
    rate = Column(Float, nullable=True)
    created_at = Column(DateTime, server_default=func.now())

    owner = relationship("User", back_populates="trips")


class Account(Base):
    """A shared, company-wide sales account — the 'hit list'. Unlike Contacts
    (private per profile, scoped by user_id), Accounts are a TEAM asset: every
    signed-in Star user sees and edits every account. `rep` marks who owns the
    relationship, not who can see it; a blank rep means unassigned (up for
    grabs). `updated_at`/`updated_by` make a cold account easy to spot and
    show who last touched it. Addresses and emails are JSON string lists so one
    account can carry several of each; customer people live in account_contacts.
    """

    __tablename__ = "accounts"

    id = Column(String, primary_key=True, default=_account_id)
    name = Column(String, nullable=False)          # company / property name
    rep = Column(String, default="")               # assigned Star salesperson; "" = unassigned
    status = Column(String, nullable=False, default="prospect")  # prospect|contacted|active|sold|dead|cod
    website = Column(String, default="")
    phone = Column(String, default="")
    addresses_json = Column(Text, default="[]")    # JSON list of address strings
    emails_json = Column(Text, default="[]")       # JSON list of account-level emails
    num_properties = Column(Integer, nullable=True)
    total_units = Column(Integer, nullable=True)   # ranking key (opportunity size)
    notes = Column(Text, default="")
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now())
    updated_by = Column(String, default="")        # name of the last editor

    contacts = relationship(
        "AccountContact",
        back_populates="account",
        cascade="all, delete-orphan",
    )
    interactions = relationship(
        "AccountInteraction",
        back_populates="account",
        cascade="all, delete-orphan",
    )


class AccountContact(Base):
    """A customer-side person under a shared Account (name, role, email, phone,
    address). Many per account, which covers the 'multiple customers / multiple
    emails' case. Created inline on the account form, or by attaching one of a
    user's personal CRM contacts (the fields are copied in, so it becomes
    team-visible on the shared account)."""

    __tablename__ = "account_contacts"

    id = Column(String, primary_key=True, default=_acct_contact_id)
    account_id = Column(
        String, ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    name = Column(String, nullable=False)
    role = Column(String, default="")
    email = Column(String, default="")
    phone = Column(String, default="")
    address = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now())

    account = relationship("Account", back_populates="contacts")


class AccountInteraction(Base):
    """A dated activity-log entry on a shared Account — the "log note" history
    (a visit, call, email, or step). Mirrors Contact.Interaction but records
    WHO logged it (`by`), since accounts are edited by the whole team.
    Cascade-deleted with the account."""

    __tablename__ = "account_interactions"

    id = Column(String, primary_key=True, default=_acct_interaction_id)
    account_id = Column(
        String, ForeignKey("accounts.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date string
    note = Column(Text, nullable=False)
    by = Column(String, default="")        # name of the user who logged it
    created_at = Column(DateTime, server_default=func.now())

    account = relationship("Account", back_populates="interactions")


def _project_id() -> str:
    return "pj" + uuid.uuid4().hex[:11]


def _proj_interaction_id() -> str:
    return "pi" + uuid.uuid4().hex[:11]


class Project(Base):
    """A large commercial construction job the PM team is running — schools,
    restaurants, retail build-outs. Shared company-wide like Account (every
    signed-in user sees and edits every project); `pm` marks who runs it, not
    who can see it. Deliberately lean: this is the "am I on top of my jobs"
    view for weekly meetings, NOT a full construction-PM system (Procore) and
    NOT accounting (QuickBooks stays the book of record for money).

    Distinct from Account: accounts are the SALES hit list (property management
    companies), projects are the PM team's active construction work. No FK
    between them — a school job comes through a GC, not a mgmt company.

    `stage` drives the board grouping; "in_progress" is the default/main lane.
    """

    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=_project_id)
    name = Column(String, nullable=False)             # job name, e.g. "Lincoln High gym floor"
    client = Column(String, default="")               # GC / owner / school district (free text)
    site_address = Column(String, default="")
    project_type = Column(String, default="other")    # school|restaurant|retail|multifamily|office|other
    stage = Column(String, nullable=False, default="in_progress")  # bidding|awarded|in_progress|punch_list|complete|lost
    pm = Column(String, default="")                   # assigned project manager; "" = unassigned
    contract_value = Column(Float, nullable=True)
    start_date = Column(String, default="")           # ISO date string, may be empty
    target_date = Column(String, default="")          # target substantial completion
    material = Column(String, default="")             # LVP / carpet / tile / mixed
    sq_ft = Column(Integer, nullable=True)
    description = Column(Text, default="")
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now())
    updated_by = Column(String, default="")           # name of the last editor

    interactions = relationship(
        "ProjectInteraction",
        back_populates="project",
        cascade="all, delete-orphan",
    )


class ProjectInteraction(Base):
    """A dated activity-log entry on a Project — the running job log (site
    visit, material delivery, delay, inspection). Mirrors AccountInteraction:
    records WHO logged it (`by`), since the whole PM team edits projects.
    This is what makes the weekly meeting easy — the log IS the status."""

    __tablename__ = "project_interactions"

    id = Column(String, primary_key=True, default=_proj_interaction_id)
    project_id = Column(
        String, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False, index=True
    )
    date = Column(String, nullable=False)  # ISO date string
    note = Column(Text, nullable=False)
    by = Column(String, default="")        # name of the user who logged it
    created_at = Column(DateTime, server_default=func.now())

    project = relationship("Project", back_populates="interactions")


def _thread_id() -> str:
    return "et" + uuid.uuid4().hex[:11]


class EmailThread(Base):
    """One triaged conversation in a user's mailbox — the Email tab's unit of
    work. NO message bodies are stored, ever (that rule is what keeps this
    table at ~1.2 KB/row instead of 5-20 KB): metadata, a 300-char snippet,
    and the triage verdict. `messages_json` keeps a compact per-message trail
    ({id, dir, from, at, toMe, ccMe}, capped at 30) so thread STATE can be
    recomputed when a new message lands without refetching history from Graph.
    Rows older than 90 days are pruned at sync time — the digest only cares
    about recent mail, and anything with lasting value gets promoted to an
    account note instead."""

    __tablename__ = "email_threads"

    id = Column(String, primary_key=True, default=_thread_id)
    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    conversation_id = Column(String, nullable=False, index=True)
    subject = Column(String, default="")
    sender_name = Column(String, default="")    # latest inbound sender
    sender_email = Column(String, default="")
    snippet = Column(String, default="")        # bodyPreview of latest inbound, capped
    folder = Column(String, default="")         # display name where it sits
    web_link = Column(String, default="")
    messages_json = Column(Text, default="[]")  # compact per-message trail (no bodies)
    last_message_id = Column(String, default="")  # triage cache key: retriage only when this changes
    last_direction = Column(String, default="in")  # in | out
    first_at = Column(String, default="")       # ISO datetime
    last_at = Column(String, default="", index=True)
    msg_count = Column(Integer, nullable=False, default=1)
    is_flagged = Column(Boolean, nullable=False, default=False)
    # Verdict
    state = Column(String, nullable=False, default="needs_reply")
    # needs_reply | waiting | fyi | resolved | bulk
    rank = Column(Integer, nullable=False, default=50)   # 0-100 within-lane ordering
    category = Column(String, default="")                # customer|vendor|internal|notification|other
    reason = Column(String, default="")                  # one line: why it ranked here (auditable)
    model_used = Column(Boolean, nullable=False, default=False)
    account_id = Column(String, nullable=True)           # matched shared account (domain match)
    account_name = Column(String, default="")
    triaged_at = Column(DateTime, server_default=func.now())
    # Dismiss: the user manually removed this from their lanes (e.g. a
    # cold pitch they don't want to reply to). When a NEW message lands
    # after dismissal (last_message_id != dismissed_at_msg_id) the dismiss
    # is cleared automatically and the thread re-surfaces.
    dismissed_at = Column(DateTime, nullable=True)
    dismissed_at_msg_id = Column(String, default="")
    created_at = Column(DateTime, server_default=func.now())


class EmailSyncState(Base):
    """Per-user Graph delta tokens + last-sync stamp. One row per user; the
    deltaLink is what makes every sync after the first incremental."""

    __tablename__ = "email_sync_state"

    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    inbox_delta = Column(Text, default="")
    sent_delta = Column(Text, default="")
    last_sync = Column(DateTime, nullable=True)


class UserPref(Base):
    """Per-user feature preferences. Digest is OFF by default — it only ever
    emails people who chose it (the Email tab's switch writes here; the phase-2
    digest job reads it)."""

    __tablename__ = "user_prefs"

    user_id = Column(
        String, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True
    )
    digest_enabled = Column(Boolean, nullable=False, default=False)
    digest_hour = Column(Integer, nullable=False, default=7)  # local (Pacific) send hour


class GlossaryEntry(Base):
    """Company vocabulary fed to the triage model — what lets a small model
    know DataNet is our IT vendor and RollMaster is the ERP. Accuracy here is
    a context problem, not a model-size problem. Seeded on first run; grows by
    hand (direct DB edits for now)."""

    __tablename__ = "glossary"

    id = Column(Integer, primary_key=True, autoincrement=True)
    term = Column(String, nullable=False)
    meaning = Column(String, nullable=False)
